export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_TRENDING_SONGS_SUCCESS = 'FETCH_TRENDING_SONGS_SUCCESS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_LAST_WEEK_EVENTS_SUCCESS = 'FETCH_LAST_WEEK_EVENTS_SUCCESS';
export const LOGOUT = 'LOGOUT';
