export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_POPULAR_SONGS_SUCCESS = 'FETCH_POPULAR_SONGS_SUCCESS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_LAST_WEEK_EVENTS_SUCCESS = 'FETCH_LAST_WEEK_EVENTS_SUCCESS';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRE_SONG_IDS = 'FETCH_GENRE_SONG_IDS';
export const SET_ACTIVE_GENRE = 'SET_ACTIVE_GENRE';
export const LOGOUT = 'LOGOUT';
